### ISSUE TITLE
gem updates

### ISSUE THREAD

**Issue by d4be4st** [infinum/default_rails_template#6]
**Development**
- [x] ~~gem 'quiet_assets'~~
- [x] gem 'better_errors'
- [x] gem 'binding_of_caller'
- [x] gem 'bullet'
- [ ] gem 'annotate
- [x] gem 'letter_opener'
- [x] gem 'pry-byebug' # for next/continue commands

**Production**
- [x] gem 'pry-rails' # for when we run console on staging/production

change thin for puma
- [x] ~~gem 'puma'~~

**Comment by mivanek** [comment]
Does it make sense to move pry-byebug to production? It's not like you can insert a breakpoint into live production code.

**Comment by DamirSvrtan** [comment]
@d4be4st - I had them at one point but decided to make it simpler. 

A couple of things:
The quiet assets is now a default in rails, so we don't need it anymore :)

Better errors and binding of caller - I'd add them only if it's an HTML app. As much as I see it, we can generate 3 types of applications:
- API APP -> --api option
- HTML APP -> --no-api option
- API & HTML APP -> no options
Based on that we can decide which gems to add where.

Why thin instead of puma? To be honest, I don't know when was the last time I ran a rails server, and I believe it was mostly with Webrick, so I don't know the development advantages of one or another.
Don't we also use Passenger in production, so maybe this should go to a group?

**Comment by DamirSvrtan** [comment]
I also wanted to add rspec, but will have to think about how much defaults we have, since it by default adds ActiveRecord stuff, which I hope we won't use in the future :)

**Comment by d4be4st** [comment]
agree with @mivanek for pry-byebug, but would leave pry-rails in default stack

@DamirSvrtan i do not know where i saw thin, but rails 5 puts puma by default. It is needed for action cable.

I am not sure about quiet_assets thou, and it would be great to not include it if we move to rails 5 anytime soon.

**Comment by DamirSvrtan** [comment]
@d4be4st I'm counting on using Rails 5 when a new Rails project comes along, so we won't need quiet_assets.

As for puma vs thin, you didn't give any valid arguments so I'm leaving the default.

I moved pry-rails to the general group of gems and added the pry-byebug to dev & test.

I'll add annotate once I add a specific task that will migrate and annotate all together.

As for the other gems, we have to agree on the conventions of generating Rails apps since they don't fit when you generate API only apps.

Btw. Is there still any benefit of using Better Errors instead of the web console?
